server:
  port: 8084

spring:
  application:
    name: claims-service
  datasource:
    url: jdbc:mysql://localhost:3309/claimsdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

axon:
  axonserver:
    servers: localhost:8124
