server:
  port: 8086

spring:
  application:
    name: eligibility-service
  datasource:
    url: jdbc:mysql://localhost:3312/eligibilitydb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans