server:
  port: 8083

spring:
  application:
    name: policy-service
  datasource:
    url: jdbc:mysql://localhost:3308/policydb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
